version: '2'
services:
  db:
    image: postgres:9.4
    volumes:
      - ./pg-data:/var/lib/postgresql
  web:
    build: .
    entrypoint: ./docker-wait-for-db.sh
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
    depends_on:
      - db
